user:
  admin:
    id: -1
    username: ENC(1hak+QtSRqr4mBHZJYSx2mUT8bchOLpf)
    password: ENC(G1d9E+0lFVNTXE6CYoATcA==)
    authorities:
      - OP_ACCESS_ADMIN
      - OP_EDIT_ADMIN
      - OP_ADD_ADMIN
      - OP_DELETE_ADMIN
      - OP_ADD_ROLE
      - OP_ACCESS_ROLE
      - OP_DELETE_ROLE
      - OP_ACCESS_USER
      - OP_EDIT_USER
      - OP_DELETE_USER
      - OP_ADD_USER
      - OP_DELETE_POST
      - OP_DELETE_COMMENT