package ir.darkdeveloper.anbarinoo.testContainers;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.extension.*;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;

//@Testcontainers
public class DatabaseSetup  implements
        BeforeAllCallback, AfterAllCallback, BeforeEachCallback, AfterEachCallback {

    // static keyword makes container for all tests, if not provided, everytime for each test, a container will be created
    // and then deleted
//    @Container
    private static PostgreSQLContainer container =
            (PostgreSQLContainer) new PostgreSQLContainer("postgres:13.1-alpine")
                    .withReuse(true);
    // statically setting properties to the spring context
//            .withDatabaseName("db")
//            .withUsername("dd")
//            .withPassword("1234");


    // Dynamically setting properties generated by container to the spring contex
    @DynamicPropertySource
    public static void overrideProps(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", container::getJdbcUrl);
        registry.add("spring.datasource.username", container::getUsername);
        registry.add("spring.datasource.password", container::getPassword);
        registry.add("spring.datasource.driver-class-name", container::getDriverClassName);
    }

    @Override
    public void afterAll(ExtensionContext context) throws Exception {

    }

    @Override
    public void afterEach(ExtensionContext context) throws Exception {

    }

    @Override
    public void beforeAll(ExtensionContext context) throws Exception {
        container.start();
    }

    @Override
    public void beforeEach(ExtensionContext context) throws Exception {

    }
}
