version: '2'

services:
  anbarinoo_app:
    image: 'anbarinoo:latest'
    build: ./app
    container_name: anbarinoo_app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - anbarinoo_db
      - anbarinoo_maildev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://anbarinoo_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  anbarinoo_db:
    image: 'postgres:14.5-alpine'
    container_name: anbarinoo_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  anbarinoo_maildev:
    image: "maildev/maildev"
    container_name: "anbarinoo_maildev"
    ports:
      - "1025:1025"
      - "1080:1080"